const account = {
  // compte enfant
  accessToken: "",
  anneeScolaireCourante: "2020-2021",
  civilite: "",
  codeOgec: "123456",
  couleurAgendaEtablissement: "#22C55E",
  dicoEnLigneLeRobert: false,
  email: "john.doe@gmail.com",
  id: 1000,
  idLogin: 1234567,
  identifiant: "john.doe",
  lastConnexion: "2021-04-18 00:00",
  logoEtablissement: "",
  main: true,
  modules: [
    {
      code: "CANTINE_BARCODE",
      enable: false,
      ordre: 1,
      badge: 0,
      params: {},
    },
    {
      code: "VIE_SCOLAIRE",
      enable: true,
      ordre: 10,
      badge: 0,
      params: {},
    },
    {
      code: "VIE_DE_LA_CLASSE",
      enable: true,
      ordre: 20,
      badge: 0,
      params: {},
    },
    {
      code: "NOTES",
      enable: true,
      ordre: 30,
      badge: 0,
      params: {},
    },
    {
      code: "CLOUD",
      enable: true,
      ordre: 90,
      badge: 0,
      params: {
        padsActif: "0",
      },
    },
    {
      code: "MESSAGERIE",
      enable: true,
      ordre: 40,
      badge: 0,
      params: {
        isActif: "1",
        canParentsLireMessagesEnfants: "1",
        destAdmin: "0",
        destEleve: "0",
        destFamille: "0",
        destProf: "1",
        destEspTravail: "0",
        disabledNotification: "0",
        notificationEmailEtablissement: "1",
        choixMailNotification: "0",
        autreMailNotification: "",
        mailPro: "",
        mailPerso: "",
        messagerieApiVersion: "v3",
        blackListProfActive: "0",
        estEnBlackList: "0",
        afficherToutesLesClasses: "0",
      },
    },
    {
      code: "EDT",
      enable: true,
      ordre: 50,
      badge: 0,
      params: {},
    },
    {
      code: "DOCUMENTS_ELEVE",
      enable: true,
      ordre: 71,
      badge: 0,
      params: {
        DocumentsNotesActif: "1",
        DocumentsVSActif: "1",
        DocumentsAdministratifActif: "1",
        AnneeArchive: "2016-2017,2017-2018,2018-2019,2019-2020,2020-2021",
      },
    },
    {
      code: "CAHIER_DE_TEXTES",
      enable: true,
      ordre: 60,
      badge: 0,
      params: {
        compteRenduSeance: "1",
        compteRenduSeancePrevisionnel: "0",
        isCDTPrimaire: "0",
      },
    },
    {
      code: "QCM",
      enable: true,
      ordre: 65,
      badge: 0,
      params: {},
    },
    {
      code: "RESERVATIONS",
      enable: false,
      ordre: 80,
      badge: 0,
      params: {
        regime: "Demi-pensionnaire",
        repasmidi_1: "1",
        repassoir_1: "0",
        repasmidi_2: "1",
        repassoir_2: "0",
        repasmidi_3: "0",
        repassoir_3: "0",
        repasmidi_4: "1",
        repassoir_4: "0",
        repasmidi_5: "1",
        repassoir_5: "0",
        repasmidi_6: "0",
        repassoir_6: "0",
        repasmidi_7: "0",
        repassoir_7: "0",
      },
    },
    {
      code: "COMMANDE_PASSAGE",
      enable: false,
      ordre: 81,
      badge: 0,
      params: {},
    },
    {
      code: "CARNET_CORRESPONDANCE",
      enable: false,
      ordre: 70,
      badge: 0,
      params: {},
    },
    {
      code: "ESIDOC",
      enable: false,
      ordre: 110,
      badge: 0,
      params: {},
    },
    {
      code: "EDUNAO",
      enable: false,
      ordre: 100,
      badge: 0,
      params: {},
    },
    {
      code: "CATER",
      enable: false,
      ordre: 90,
      badge: 0,
      params: {},
    },
    {
      code: "ARD",
      enable: false,
      ordre: 120,
      badge: 0,
      params: {},
    },
    {
      code: "PEARLTREES",
      enable: false,
      ordre: 170,
      badge: 0,
      params: {},
    },
    {
      code: "EDUMALIN",
      enable: false,
      ordre: 171,
      badge: 0,
      params: {},
    },
    {
      code: "SUIVI_STAGE",
      enable: false,
      ordre: 43,
      badge: 0,
      params: {},
    },
    {
      code: "CLICKNPLAY",
      enable: false,
      ordre: 171,
      badge: 0,
      params: {},
    },
    {
      code: "VOLTAIRE",
      enable: false,
      ordre: 175,
      badge: 0,
      params: {},
    },
    {
      code: "ONISEPSERVICES",
      enable: false,
      ordre: 172,
      badge: 0,
      params: {},
    },
    {
      code: "AVENRIA",
      enable: false,
      ordre: 173,
      badge: 0,
      params: {},
    },
    {
      code: "SACOCHE",
      enable: false,
      ordre: 174,
      badge: 0,
      params: {},
    },
    {
      code: "ETUDIANT",
      enable: false,
      ordre: 176,
      badge: 0,
      params: {},
    },
    {
      code: "IJBOX",
      enable: false,
      ordre: 177,
      badge: 0,
      params: {},
    },
    {
      code: "SITUATION_FINANCIERE",
      enable: false,
      ordre: 92,
      badge: 0,
      params: {},
    },
  ],
  nom: "DOE",
  nomEtablissement: "Saint Anne",
  parametresIndividuels: {
    isQrcode: false,
    lsuPoilDansLaMainBorne1: "",
    lsuPoilDansLaMainBorne2: "",
    lsuPoilDansLaMainBorne3: "",
    modeAccessibiliteVisuelle: false,
    modeCalculLSU: "",
    nbJoursMaxRenduDevoirCDT: "",
    typeSaisieNotesDefaut: "",
    typeViewCDTDefaut: "",
  },
  particule: "",
  prenom: "John",
  profile: {
    classe: {
      code: "2A",
      id: 50,
      libelle: "Seconde A",
    },
    idEtablissement: "0",
    idReelEtab: "2",
    infoEDT: "",
    nomEtablissement: "Saint Anne",
    photo: "https://picsum.photos/200/300",
    rneEtablissement: "1597863F",
    sexe: "M",
  },
  typeCompte: "E",
  uid: "6ef6f7ee-9fbe-427f-a674-f9b3333e3091",
};

export default account;
