const events = [
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "PH-CH",
    color: "#ffc3ca",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 162817,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "PHYSIQUE-CHIMIE",
    prof: "MOUREY S.",
    salle: "M01 PC-VPI",
    start_date: "%d %h",
    text: "PHYSIQUE-CHIMIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "EPS",
    color: "#cf9ced",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 20221,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "ED.PHYSIQUE & SPORT.",
    prof: "MOREL M.",
    salle: "",
    start_date: "%d %h",
    text: "ED.PHYSIQUE & SPORT.",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "MATHS",
    color: "#ffb9b9",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 66550,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "MATHEMATIQUES",
    prof: "TRICOT S.",
    salle: "R01-VPI",
    start_date: "%d %h",
    text: "MATHEMATIQUES",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "PHILO",
    color: "#c4cfff",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 28621,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "PHILOSOPHIE",
    prof: "GAUTIER M.",
    salle: "C11-V",
    start_date: "%d %h",
    text: "PHILOSOPHIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "CONT",
    color: "#91b2bc",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 34071,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "Contrôle",
    prof: "",
    salle: "",
    start_date: "%d %h",
    text: "Contrôle",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "HI-GE",
    color: "#91b2bc",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 63087,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "HISTOIRE-GEOGRAPHIE",
    prof: "BROISAT A.",
    salle: "M05-V",
    start_date: "%d %h",
    text: "HISTOIRE-GEOGRAPHIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "HI-GE",
    color: "#91b2bc",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 156271,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "HISTOIRE-GEOGRAPHIE",
    prof: "BROISAT A.",
    salle: "P01-MV",
    start_date: "%d %h",
    text: "HISTOIRE-GEOGRAPHIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "HI-GE",
    color: "#91b2bc",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 41433,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "HISTOIRE-GEOGRAPHIE",
    prof: "BROISAT A.",
    salle: "M04-VPI",
    start_date: "%d %h",
    text: "HISTOIRE-GEOGRAPHIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "PH-CH",
    color: "#ffc3ca",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 16975,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "PHYSIQUE-CHIMIE",
    prof: "MOUREY S.",
    salle: "M01 PC-VPI",
    start_date: "%d %h",
    text: "PHYSIQUE-CHIMIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "MATHS",
    color: "#ffb9b9",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 152731,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "MATHEMATIQUES",
    prof: "TRICOT S.",
    salle: "M01 PC-VPI",
    start_date: "%d %h",
    text: "MATHEMATIQUES",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "MATHS",
    color: "#ffb9b9",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 59217,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "MATHEMATIQUES",
    prof: "TRICOT S.",
    salle: "M01 PC-VPI",
    start_date: "%d %h",
    text: "MATHEMATIQUES",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "ACHOR",
    color: "#91b2bc",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 48086,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "ACCOMP.CHOIX ORIENT.",
    prof: "TRICOT S.",
    salle: "R01-VPI",
    start_date: "%d %h",
    text: "ACCOMP.CHOIX ORIENT.",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "HI-GE",
    color: "#91b2bc",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 81722,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "HISTOIRE-GEOGRAPHIE",
    prof: "BROISAT A.",
    salle: "R01-VPI",
    start_date: "%d %h",
    text: "HISTOIRE-GEOGRAPHIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "PHILO",
    color: "#c4cfff",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 47104,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "PHILOSOPHIE",
    prof: "GAUTIER M.",
    salle: "M12-VPI",
    start_date: "%d %h",
    text: "PHILOSOPHIE",
    typeCours: "COURS",
  },
  {
    classe: "Seconde A",
    classeCode: "2A",
    classeId: 50,
    codeMatiere: "PHILO",
    color: "#c4cfff",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "",
    groupeCode: "",
    groupeId: 0,
    icone: "",
    id: 157660,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "PHILOSOPHIE",
    prof: "GAUTIER M.",
    salle: "P05-MV",
    start_date: "%d %h",
    text: "PHILOSOPHIE",
    typeCours: "COURS",
  },
  {
    classe: "",
    classeCode: "",
    classeId: 0,
    codeMatiere: "SVT",
    color: "#fecddb",
    contenuDeSeance: false,
    devoirAFaire: false,
    dispensable: false,
    dispense: 0,
    end_date: "%d %h",
    groupe: "2AP2",
    groupeCode: "2AP2",
    groupeId: 630,
    icone: "",
    id: 38012,
    isAnnule: false,
    isFlexible: false,
    isModifie: false,
    matiere: "SCIENCES VIE & TERRE",
    prof: "BOUVATTIER B.",
    salle: "R11-SVT-VPI",
    start_date: "%d %h",
    text: "SCIENCES VIE & TERRE",
    typeCours: "COURS",
  },
];

const hours = [
"08:30",
"09:25",
"10:20",
"11:20",
"12:30",
"13:30",
"14:25",
"15:30",
"16:30",
"17:30",
]
const agenda = (date: string): any[] => {
  const o = [];
  for (let index = 0; index < 5; index++) {
    o.push(events[Math.floor(Math.random()*events.length)]);
  }
  var i = 0;
  var _hours = hours;
  o.forEach(e => {
    e.start_date = e.start_date.replace("%d", date);
    e.end_date = e.end_date.replace("%d", date);
    e.start_date = e.start_date.replace("%h", _hours[i]);
    e.end_date = e.end_date.replace("%h", _hours[i+Math.floor(Math.random()*2)+1 ]);
    i++;
  });

  return o;
};

export default agenda;
