const agenda = (date:String) => [
  {
    id: 20221,
    text: "ED.PHYSIQUE & SPORT.",
    matiere: "ED.PHYSIQUE & SPORT.",
    codeMatiere: "EPS",
    typeCours: "COURS",
    start_date: `${date} 15:40`,
    end_date: `${date} 17:30`,
    color: "#cf9ced",
    dispensable: false,
    dispense: 0,
    prof: "MOREL M.",
    salle: "",
    classe: "Seconde A",
    classeId: 50,
    classeCode: "2A",
    groupe: "",
    groupeCode: "",
    isFlexible: false,
    groupeId: 0,
    icone: "",
    isModifie: false,
    contenuDeSeance: false,
    devoirAFaire: false,
    isAnnule: false,
  },
  {
    id: 28621,
    text: "PHILOSOPHIE",
    matiere: "PHILOSOPHIE",
    codeMatiere: "PHILO",
    typeCours: "COURS",
    start_date: `${date} 11:30`,
    end_date: `${date} 12:25`,
    color: "#c4cfff",
    dispensable: false,
    dispense: 0,
    prof: "GAUTIER M.",
    salle: "C11-V",
    classe: "Seconde A",
    classeId: 50,
    classeCode: "2A",
    groupe: "",
    groupeCode: "",
    isFlexible: false,
    groupeId: 0,
    icone: "",
    isModifie: false,
    contenuDeSeance: false,
    devoirAFaire: false,
    isAnnule: false,
  },
  {
    id: 63087,
    text: "HISTOIRE-GEOGRAPHIE",
    matiere: "HISTOIRE-GEOGRAPHIE",
    codeMatiere: "HI-GE",
    typeCours: "COURS",
    start_date: `${date} 09:25`,
    end_date: `${date} 10:20`,
    color: "#91b2bc",
    dispensable: false,
    dispense: 0,
    prof: "BROISAT A.",
    salle: "M05-V",
    classe: "Seconde A",
    classeId: 50,
    classeCode: "2A",
    groupe: "",
    groupeCode: "",
    isFlexible: false,
    groupeId: 0,
    icone: "",
    isModifie: false,
    contenuDeSeance: false,
    devoirAFaire: false,
    isAnnule: false,
  },
  {
    id: 41433,
    text: "HISTOIRE-GEOGRAPHIE",
    matiere: "HISTOIRE-GEOGRAPHIE",
    codeMatiere: "HI-GE",
    typeCours: "COURS",
    start_date: `${date} 08:30`,
    end_date: `${date} 09:25`,
    color: "#91b2bc",
    dispensable: false,
    dispense: 0,
    prof: "BROISAT A.",
    salle: "M04-VPI",
    classe: "Seconde A",
    classeId: 50,
    classeCode: "2A",
    groupe: "",
    groupeCode: "",
    isFlexible: false,
    groupeId: 0,
    icone: "",
    isModifie: false,
    contenuDeSeance: false,
    devoirAFaire: false,
    isAnnule: false,
  },
  {
    id: 59217,
    text: "MATHEMATIQUES",
    matiere: "MATHEMATIQUES",
    codeMatiere: "MATHS",
    typeCours: "COURS",
    start_date: `${date} 13:40`,
    end_date: `${date} 15:30`,
    color: "#ffb9b9",
    dispensable: false,
    dispense: 0,
    prof: "TRICOT S.",
    salle: "M01 PC-VPI",
    classe: "Seconde A",
    classeId: 50,
    classeCode: "2A",
    groupe: "",
    groupeCode: "",
    isFlexible: false,
    groupeId: 0,
    icone: "",
    isModifie: false,
    contenuDeSeance: false,
    devoirAFaire: false,
    isAnnule: false,
  },
  {
    id: 7898,
    text: "ESPAGNOL LV2",
    matiere: "ESPAGNOL LV2",
    codeMatiere: "ESP2",
    typeCours: "COURS",
    start_date: `${date} 10:35`,
    end_date: `${date} 11:30`,
    color: "#fde578",
    dispensable: false,
    dispense: 0,
    prof: "MARTINY C.",
    salle: "C02-VPI",
    classe: "",
    classeId: 0,
    classeCode: "",
    groupe: "2AESP2",
    groupeCode: "2AESP2",
    isFlexible: false,
    groupeId: 689,
    icone: "",
    isModifie: false,
    contenuDeSeance: false,
    devoirAFaire: false,
    isAnnule: false,
  },
];

export default agenda;
