const contacts = [
  {
    civilite: "M.",
    prenom: "Philippe",
    particule: "",
    nom: "MARTIN",
    sexe: "",
    id: 100,
    type: "P",
    matiere: "",
    photo: "",
    telephone: "",
    email: "",
    estBlackList: false,
    isPP: false,
    etablissements: [],
    classes: [
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "DIRECTEUR",
      },
    ],
    classe: {
      id: 0,
      code: "",
      libelle: "",
    },
    responsable: {
      id: 0,
      versQui: "",
      typeResp: "",
      contacts: [],
    },
    fonction: {
      id: 0,
      libelle: "",
    },
  },
  {
    civilite: "M.",
    prenom: "Jérôme",
    particule: "",
    nom: "BERNARD",
    sexe: "",
    id: 79,
    type: "P",
    matiere: "",
    photo: "",
    telephone: "",
    email: "",
    estBlackList: false,
    isPP: false,
    etablissements: [],
    classes: [
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "NUMERIQUE SC.INFORM.",
      },
    ],
    classe: {
      id: 0,
      code: "",
      libelle: "",
    },
    responsable: {
      id: 0,
      versQui: "",
      typeResp: "",
      contacts: [],
    },
    fonction: {
      id: 0,
      libelle: "",
    },
  },
  {
    civilite: "Mme",
    prenom: "Elodie",
    particule: "",
    nom: "THOMAS",
    sexe: "",
    id: 179,
    type: "P",
    matiere: "",
    photo: "",
    telephone: "",
    email: "",
    estBlackList: false,
    isPP: false,
    etablissements: [],
    classes: [
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "ANGLAIS LV SECTION",
      },
    ],
    classe: {
      id: 0,
      code: "",
      libelle: "",
    },
    responsable: {
      id: 0,
      versQui: "",
      typeResp: "",
      contacts: [],
    },
    fonction: {
      id: 0,
      libelle: "",
    },
  },
  {
    civilite: "M.",
    prenom: "Francis",
    particule: "",
    nom: "PETIT",
    sexe: "",
    id: 80,
    type: "P",
    matiere: "",
    photo: "",
    telephone: "",
    email: "",
    estBlackList: false,
    isPP: false,
    etablissements: [],
    classes: [
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "PHYSIQUE-CHIMIE",
      },
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "NUMERIQUE SC.INFORM.",
      },
    ],
    classe: {
      id: 0,
      code: "",
      libelle: "",
    },
    responsable: {
      id: 0,
      versQui: "",
      typeResp: "",
      contacts: [],
    },
    fonction: {
      id: 0,
      libelle: "",
    },
  },
  {
    civilite: "Mme",
    prenom: "Marie-Emilie",
    particule: "",
    nom: "PETIT",
    sexe: "",
    id: 218,
    type: "P",
    matiere: "",
    photo: "",
    telephone: "",
    email: "",
    estBlackList: false,
    isPP: false,
    etablissements: [],
    classes: [
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "HISTOIRE-GEOGRAPHIE",
      },
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "ENS. MORAL & CIVIQUE",
      },
    ],
    classe: {
      id: 0,
      code: "",
      libelle: "",
    },
    responsable: {
      id: 0,
      versQui: "",
      typeResp: "",
      contacts: [],
    },
    fonction: {
      id: 0,
      libelle: "",
    },
  },
  {
    civilite: "Mme",
    prenom: "Sophie",
    particule: "",
    nom: "ROBERT",
    sexe: "",
    id: 142,
    type: "P",
    matiere: "",
    photo: "",
    telephone: "",
    email: "",
    estBlackList: false,
    isPP: true,
    etablissements: [],
    classes: [
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: true,
        matiere: "LCA LATIN",
      },
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "FRANCAIS",
      },
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "ACCOMPAGNEMT. PERSO.",
      },
      {
        id: 48,
        code: "",
        libelle: "Seconde A",
        isPP: false,
        matiere: "HUMAN.LITTER.PHILO.",
      },
    ],
    classe: {
      id: 0,
      code: "",
      libelle: "",
    },
    responsable: {
      id: 0,
      versQui: "",
      typeResp: "",
      contacts: [],
    },
    fonction: {
      id: 0,
      libelle: "",
    },
  },
];

export default contacts;
