const disciplines = [
  {
    id: 2176,
    codeMatiere: "FRANC",
    codeSousMatiere: "",
    discipline: "FRANCAIS",
    moyenne: "15,63",
    moyenneClasse: "12,79",
    moyenneMin: "10",
    moyenneMax: "18,75",
    coef: 1,
    effectif: 29,
    rang: 29,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 142,
        nom: "Mme MARTIN",
      },
    ],
  },
  {
    id: 2242,
    codeMatiere: "HI-GE",
    codeSousMatiere: "",
    discipline: "HISTOIRE-GEOGRAPHIE",
    moyenne: "15,5",
    moyenneClasse: "14,05",
    moyenneMin: "8,25",
    moyenneMax: "18,5",
    coef: 1,
    effectif: 29,
    rang: 29,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 218,
        nom: "Mme BERNARD",
      },
    ],
  },
  {
    id: 2194,
    codeMatiere: "AGL1",
    codeSousMatiere: "",
    discipline: "ANGLAIS LV1",
    moyenne: "18,6",
    moyenneClasse: "15",
    moyenneMin: "9,4",
    moyenneMax: "19,6",
    coef: 1,
    effectif: 29,
    rang: 29,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 98,
        nom: "Mme THOMAS",
      },
    ],
  },
  {
    id: 2177,
    codeMatiere: "ESP2",
    codeSousMatiere: "",
    discipline: "ESPAGNOL LV2",
    moyenne: "19,61",
    moyenneClasse: "16,14",
    moyenneMin: "12,06",
    moyenneMax: "19,61",
    coef: 1,
    effectif: 18,
    rang: 18,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 74,
        nom: "Mme PETIT",
      },
    ],
  },
  {
    id: 2172,
    codeMatiere: "ENSC",
    codeSousMatiere: "",
    discipline: "ENSEIGNEMENT SCIENTIFIQUE",
    moyenne: "18,75",
    moyenneClasse: "14,58",
    moyenneMin: "7,75",
    moyenneMax: "19,5",
    coef: 1,
    effectif: 29,
    rang: 29,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 17,
        nom: "M. ROBERT",
      },
      {
        id: 224,
        nom: "M. RICHARD",
      },
    ],
  },
  {
    id: 2193,
    codeMatiere: "EPS",
    codeSousMatiere: "",
    discipline: "ED.PHYSIQUE & SPORT.",
    moyenne: "16,5",
    moyenneClasse: "16,65",
    moyenneMin: "15",
    moyenneMax: "18,5",
    coef: 1,
    effectif: 29,
    rang: 29,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 34,
        nom: "Mme DURAND",
      },
    ],
  },
  {
    id: 2180,
    codeMatiere: "MATHS",
    codeSousMatiere: "",
    discipline: "MATHEMATIQUES",
    moyenne: "17,05",
    moyenneClasse: "",
    moyenneMin: "",
    moyenneMax: "",
    coef: 1,
    effectif: 0,
    rang: 0,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 35,
        nom: "M. DUBOIS",
      },
    ],
  },
  {
    id: 2191,
    codeMatiere: "NSINF",
    codeSousMatiere: "",
    discipline: "NUMERIQUE SC.INFORM.",
    moyenne: "16,64",
    moyenneClasse: "",
    moyenneMin: "",
    moyenneMax: "",
    coef: 1,
    effectif: 0,
    rang: 0,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 80,
        nom: "M. MOREAU",
      },
      {
        id: 79,
        nom: "M. LAURENT",
      },
    ],
  },
  {
    id: 2183,
    codeMatiere: "PH-CH",
    codeSousMatiere: "",
    discipline: "PHYSIQUE-CHIMIE",
    moyenne: "16,67",
    moyenneClasse: "",
    moyenneMin: "",
    moyenneMax: "",
    coef: 1,
    effectif: 0,
    rang: 0,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 80,
        nom: "M. SIMON",
      },
    ],
  },
  {
    id: 2195,
    codeMatiere: "AGL9",
    codeSousMatiere: "",
    discipline: "ANGLAIS LV SECTION",
    moyenne: "18",
    moyenneClasse: "18,38",
    moyenneMin: "17,33",
    moyenneMax: "19,17",
    coef: 1,
    effectif: 29,
    rang: 29,
    groupeMatiere: false,
    idGroupeMatiere: 0,
    option: 0,
    sousMatiere: false,
    saisieAppreciationSSMat: false,
    professeurs: [
      {
        id: 76,
        nom: "Mme MICHEL",
      },
      {
        id: 179,
        nom: "Mme LEFEVRE",
      },
    ],
  },
];

const pp = "Mme LEROY";

const periodes = [
  {
    idPeriode: "A001",
    codePeriode: "A001",
    periode: "Trimestre 1",
    annuel: false,
    dateDebut: "2020-09-02",
    dateFin: "2020-11-20",
    examenBlanc: false,
    cloture: true,
    heureConseil: "18:00",
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2020-11-23 16:46",
      moyenneGenerale: "17,29",
      moyenneClasse: "14,69",
      moyenneMin: "12,12",
      moyenneMax: "18,13",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A001R001",
    codePeriode: "A001R001",
    periode: "Relevé ",
    annuel: false,
    dateDebut: "2020-09-02",
    dateFin: "2020-10-07",
    examenBlanc: false,
    cloture: true,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2020-11-23 16:46",
      moyenneGenerale: "16,75",
      moyenneClasse: "14,15",
      moyenneMin: "11,24",
      moyenneMax: "18,06",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A001R002",
    codePeriode: "A001R002",
    periode: "Relevé ",
    annuel: false,
    dateDebut: "2020-10-08",
    dateFin: "2020-11-20",
    examenBlanc: false,
    cloture: true,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2020-11-23 16:46",
      moyenneGenerale: "17,68",
      moyenneClasse: "14,82",
      moyenneMin: "12,12",
      moyenneMax: "18,57",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A002",
    codePeriode: "A002",
    periode: "Trimestre 2",
    annuel: false,
    dateDebut: "2020-11-23",
    dateFin: "2021-02-19",
    examenBlanc: false,
    cloture: true,
    dateConseil: "2021-02-19",
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2021-03-04 09:36",
      moyenneGenerale: "17,01",
      moyenneClasse: "15,25",
      moyenneMin: "12,09",
      moyenneMax: "18,57",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A002R001",
    codePeriode: "A002R001",
    periode: "Relevé ",
    annuel: false,
    dateDebut: "2020-11-23",
    dateFin: "2021-01-08",
    examenBlanc: false,
    cloture: true,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2021-03-04 09:35",
      moyenneGenerale: "16,73",
      moyenneClasse: "14,66",
      moyenneMin: "11,52",
      moyenneMax: "18,01",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A002R002",
    codePeriode: "A002R002",
    periode: "Relevé ",
    annuel: false,
    dateDebut: "2021-01-11",
    dateFin: "2021-02-19",
    examenBlanc: false,
    cloture: true,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2021-03-04 09:36",
      moyenneGenerale: "17,19",
      moyenneClasse: "15,56",
      moyenneMin: "12,43",
      moyenneMax: "18,98",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A003",
    codePeriode: "A003",
    periode: "Trimestre 3",
    annuel: false,
    dateDebut: "2021-03-01",
    dateFin: "2021-07-03",
    examenBlanc: false,
    cloture: false,
    dateConseil: "2021-06-11",
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2021-04-17 04:04",
      moyenneGenerale: "16,66",
      moyenneClasse: "15,33",
      moyenneMin: "11,1",
      moyenneMax: "18,69",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A003R001",
    codePeriode: "A003R001",
    periode: "Relevé ",
    annuel: false,
    dateDebut: "2021-03-01",
    dateFin: "2021-05-05",
    examenBlanc: false,
    cloture: false,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2021-04-17 04:04",
      moyenneGenerale: "16,66",
      moyenneClasse: "15,33",
      moyenneMin: "11,09",
      moyenneMax: "18,69",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A003R002",
    codePeriode: "A003R002",
    periode: "Relevé ",
    annuel: false,
    dateDebut: "2021-05-06",
    dateFin: "2021-07-03",
    examenBlanc: false,
    cloture: false,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "",
      moyenneGenerale: "",
      moyenneClasse: "",
      moyenneMin: "",
      moyenneMax: "",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
  {
    idPeriode: "A999Z",
    codePeriode: "A999Z",
    periode: "Année",
    annuel: true,
    dateDebut: "2020-09-02",
    dateFin: "2021-07-03",
    examenBlanc: false,
    cloture: false,
    moyNbreJoursApresConseil: -1,
    ensembleMatieres: {
      dateCalcul: "2021-04-17 04:04",
      moyenneGenerale: "16,99",
      moyenneClasse: "15,09",
      moyenneMin: "11,82",
      moyenneMax: "18,46",
      nomPP: pp,
      nomCE: "",
      decisionDuConseil: "",
      disciplines: disciplines,
      disciplinesSimulation: [],
    },
  },
];

const notes = [
  {
    devoir: "Évaluation de connaissances - S1",
    codePeriode: "A001",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "9",
    nonSignificatif: false,
    date: "2020-09-14",
    dateSaisie: "2020-09-19",
    valeurisee: false,
    moyenneClasse: "7.68",
    minClasse: "3.50",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Interro n° 1",
    codePeriode: "A001",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "12",
    nonSignificatif: false,
    date: "2020-09-18",
    dateSaisie: "2020-09-22",
    valeurisee: false,
    moyenneClasse: "12.22",
    minClasse: "3.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Interrogation de cours",
    codePeriode: "A001",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2020-09-27",
    dateSaisie: "2020-09-27",
    valeurisee: false,
    moyenneClasse: "15.26",
    minClasse: "10.50",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "Commentaire Adieu",
    codePeriode: "A001",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "13",
    nonSignificatif: false,
    date: "2020-09-28",
    dateSaisie: "2020-09-28",
    valeurisee: false,
    moyenneClasse: "10.07",
    minClasse: "5.00",
    maxClasse: "19.00",
    elementsProgramme: [],
  },
  {
    devoir: "QCM encodage donnees part1",
    codePeriode: "A001",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "13",
    valeur: "9",
    nonSignificatif: false,
    date: "2020-10-01",
    dateSaisie: "2020-10-01",
    valeurisee: false,
    moyenneClasse: "10.44",
    minClasse: "3.00",
    maxClasse: "13.00",
    elementsProgramme: [],
  },
  {
    devoir: "TP combustion de la paraffine",
    codePeriode: "A001",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "15,5",
    nonSignificatif: false,
    date: "2020-10-02",
    dateSaisie: "2020-10-05",
    valeurisee: false,
    moyenneClasse: "13.19",
    minClasse: "10.50",
    maxClasse: "15.50",
    elementsProgramme: [],
  },
  {
    devoir: "DS n° 1",
    codePeriode: "A001",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "17,75",
    nonSignificatif: false,
    date: "2020-10-02",
    dateSaisie: "2020-10-05",
    valeurisee: false,
    moyenneClasse: "13.99",
    minClasse: "9.25",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "DS n°1",
    codePeriode: "A001",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "2",
    noteSur: "20",
    valeur: "15,5",
    nonSignificatif: false,
    date: "2020-10-05",
    dateSaisie: "2020-10-11",
    valeurisee: false,
    moyenneClasse: "9.84",
    minClasse: "2.00",
    maxClasse: "17.50",
    elementsProgramme: [],
  },
  {
    devoir: "Compréhension orale ",
    codePeriode: "A001",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-10-05",
    dateSaisie: "2020-10-05",
    valeurisee: false,
    moyenneClasse: "13.31",
    minClasse: "5.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Compréhension_orale",
    codePeriode: "A001",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Examen Blanc",
    enLettre: false,
    coef: "1.5",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2020-10-05",
    dateSaisie: "2020-10-09",
    valeurisee: false,
    moyenneClasse: "15.78",
    minClasse: "9.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "radioactivité",
    codePeriode: "A001",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19,5",
    nonSignificatif: false,
    date: "2020-10-06",
    dateSaisie: "2020-10-06",
    valeurisee: false,
    moyenneClasse: "15.48",
    minClasse: "7.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Expression orale tâche finale ",
    codePeriode: "A001",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Interro orales",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2020-10-13",
    dateSaisie: "2020-10-13",
    valeurisee: false,
    moyenneClasse: "16.40",
    minClasse: "9.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "The trial of Robespierre",
    codePeriode: "A001",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "17,5",
    nonSignificatif: false,
    date: "2020-10-15",
    dateSaisie: "2020-10-16",
    valeurisee: false,
    moyenneClasse: "17.66",
    minClasse: "16.00",
    maxClasse: "19.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS 1 Algo",
    codePeriode: "A001",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19,75",
    nonSignificatif: false,
    date: "2020-10-15",
    dateSaisie: "2020-10-15",
    valeurisee: false,
    moyenneClasse: "15.18",
    minClasse: "6.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Tableau avancement",
    codePeriode: "A001",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.25",
    noteSur: "5",
    valeur: "5",
    nonSignificatif: false,
    date: "2020-10-16",
    dateSaisie: "2020-10-13",
    valeurisee: false,
    moyenneClasse: "4.28",
    minClasse: "0.50",
    maxClasse: "5.00",
    elementsProgramme: [],
  },
  {
    devoir: "Voca_seq1_seq2",
    codePeriode: "A001",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2020-10-16",
    dateSaisie: "2020-10-16",
    valeurisee: false,
    moyenneClasse: "15.47",
    minClasse: "5.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "D.S. type bac",
    codePeriode: "A001",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "2",
    noteSur: "20",
    valeur: "15",
    nonSignificatif: false,
    date: "2020-10-16",
    dateSaisie: "2020-10-16",
    valeurisee: false,
    moyenneClasse: "12.03",
    minClasse: "8.00",
    maxClasse: "18.00",
    elementsProgramme: [],
  },
  {
    devoir: "Anthologie poétique",
    codePeriode: "A001",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2020-10-28",
    dateSaisie: "2020-10-28",
    valeurisee: false,
    moyenneClasse: "16.36",
    minClasse: "12.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Evaluation Radioactivité-Cristaux",
    codePeriode: "A001",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-10-30",
    dateSaisie: "2020-10-30",
    valeurisee: false,
    moyenneClasse: "13.82",
    minClasse: "5.00",
    maxClasse: "19.00",
    elementsProgramme: [],
  },
  {
    devoir: "Évaluation - Analyse de documents",
    codePeriode: "A001",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "8",
    nonSignificatif: false,
    date: "2020-11-02",
    dateSaisie: "2020-11-04",
    valeurisee: false,
    moyenneClasse: "6.43",
    minClasse: "3.50",
    maxClasse: "9.00",
    elementsProgramme: [],
  },
  {
    devoir: "Final Project 1 The Amazing Race",
    codePeriode: "A001",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18,5",
    nonSignificatif: false,
    date: "2020-11-05",
    dateSaisie: "2020-11-05",
    valeurisee: false,
    moyenneClasse: "18.74",
    minClasse: "18.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS n° 2",
    codePeriode: "A001",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2020-11-06",
    dateSaisie: "2020-11-11",
    valeurisee: false,
    moyenneClasse: "11.97",
    minClasse: "7.50",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "Projet_affiche_EE",
    codePeriode: "A001",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1.5",
    noteSur: "20",
    valeur: "19,5",
    nonSignificatif: false,
    date: "2020-11-09",
    dateSaisie: "2020-11-08",
    valeurisee: false,
    moyenneClasse: "17.64",
    minClasse: "12.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS n°2",
    codePeriode: "A001",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "2",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-11-09",
    dateSaisie: "2020-11-15",
    valeurisee: false,
    moyenneClasse: "14.77",
    minClasse: "6.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Exposés",
    codePeriode: "A001",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "9,5",
    nonSignificatif: false,
    date: "2020-11-10",
    dateSaisie: "2020-11-10",
    valeurisee: false,
    moyenneClasse: "8.84",
    minClasse: "7.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Investment 1st period",
    codePeriode: "A001",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-11-12",
    dateSaisie: "2020-11-16",
    valeurisee: false,
    moyenneClasse: "17.69",
    minClasse: "14.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "musculation",
    codePeriode: "A001",
    codeMatiere: "EPS",
    libelleMatiere: "ED.PHYSIQUE & SPORT.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "16,5",
    nonSignificatif: false,
    date: "2020-11-14",
    dateSaisie: "2020-11-14",
    valeurisee: false,
    moyenneClasse: "16.65",
    minClasse: "15.00",
    maxClasse: "18.50",
    elementsProgramme: [],
  },
  {
    devoir: "Évaluation de connaissances - G1",
    codePeriode: "A001",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "6",
    nonSignificatif: false,
    date: "2020-11-16",
    dateSaisie: "2020-11-14",
    valeurisee: false,
    moyenneClasse: "6.93",
    minClasse: "4.00",
    maxClasse: "9.00",
    elementsProgramme: [],
    qcm: {
      idQCM: 112,
      idAssociation: 75,
      titre:
        "QCM : Métropoles coeur de la mondialisation, diversité et inégalités — 1D",
      debute: "2020-11-16 08:09:22",
    },
  },
  {
    devoir: "eval n°2",
    codePeriode: "A001",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "19",
    valeur: "15,5",
    nonSignificatif: false,
    date: "2020-11-16",
    dateSaisie: "2020-11-16",
    valeurisee: false,
    moyenneClasse: "13.00",
    minClasse: "7.50",
    maxClasse: "18.00",
    elementsProgramme: [],
  },
  {
    devoir: "Interro n° 2",
    codePeriode: "A001",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.25",
    noteSur: "20",
    valeur: "16,5",
    nonSignificatif: false,
    date: "2020-11-17",
    dateSaisie: "2020-11-19",
    valeurisee: false,
    moyenneClasse: "11.66",
    minClasse: "1.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Implication_classe",
    codePeriode: "A001",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "10",
    nonSignificatif: false,
    date: "2020-11-19",
    dateSaisie: "2020-11-19",
    valeurisee: false,
    moyenneClasse: "7.06",
    minClasse: "5.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "critallo",
    codePeriode: "A002",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "15,5",
    nonSignificatif: false,
    date: "2020-11-24",
    dateSaisie: "2020-11-30",
    valeurisee: false,
    moyenneClasse: "13.59",
    minClasse: "2.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "IE de lecture",
    codePeriode: "A002",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "7",
    nonSignificatif: false,
    date: "2020-11-24",
    dateSaisie: "2020-11-26",
    valeurisee: false,
    moyenneClasse: "7.74",
    minClasse: "3.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Interro n° 3",
    codePeriode: "A002",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.25",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2020-11-27",
    dateSaisie: "2020-11-30",
    valeurisee: false,
    moyenneClasse: "15.59",
    minClasse: "8.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Transposer un texte en croquis",
    codePeriode: "A002",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "7,5",
    nonSignificatif: false,
    date: "2020-11-27",
    dateSaisie: "2020-11-29",
    valeurisee: false,
    moyenneClasse: "5.95",
    minClasse: "4.50",
    maxClasse: "8.00",
    elementsProgramme: [],
  },
  {
    devoir: "questionnaire SJP",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-12-03",
    dateSaisie: "2020-12-03",
    valeurisee: false,
    moyenneClasse: "15.59",
    minClasse: "8.00",
    maxClasse: "19.75",
    elementsProgramme: [],
  },
  {
    devoir: "Bilan FDM",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "8",
    nonSignificatif: false,
    date: "2020-12-03",
    dateSaisie: "2020-12-03",
    valeurisee: false,
    moyenneClasse: "7.64",
    minClasse: "4.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Compréhension écrite ",
    codePeriode: "A002",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Examen Blanc",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "16",
    nonSignificatif: false,
    date: "2020-12-07",
    dateSaisie: "2020-12-07",
    valeurisee: false,
    moyenneClasse: "13.72",
    minClasse: "7.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Évaluation de grammaire et vocabulaire ",
    codePeriode: "A002",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "17,75",
    nonSignificatif: false,
    date: "2020-12-07",
    dateSaisie: "2020-12-07",
    valeurisee: false,
    moyenneClasse: "14.45",
    minClasse: "8.75",
    maxClasse: "19.75",
    elementsProgramme: [],
  },
  {
    devoir: "Connaissances Thème 1",
    codePeriode: "A002",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "8",
    nonSignificatif: false,
    date: "2020-12-08",
    dateSaisie: "2020-12-10",
    valeurisee: false,
    moyenneClasse: "7.48",
    minClasse: "4.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Interro n° 4",
    codePeriode: "A002",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "19,5",
    nonSignificatif: false,
    date: "2020-12-08",
    dateSaisie: "2020-12-16",
    valeurisee: false,
    moyenneClasse: "15.93",
    minClasse: "5.00",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "Dissertation",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "14",
    nonSignificatif: false,
    date: "2020-12-09",
    dateSaisie: "2020-12-09",
    valeurisee: false,
    moyenneClasse: "11.93",
    minClasse: "7.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS2 Algo",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-12-10",
    dateSaisie: "2021-01-12",
    valeurisee: false,
    moyenneClasse: "13.67",
    minClasse: "5.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "QCM IHM - Web",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2020-12-10",
    dateSaisie: "2021-01-01",
    valeurisee: false,
    moyenneClasse: "15.67",
    minClasse: "11.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Bilan grammaire",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "36",
    valeur: "28,5",
    nonSignificatif: false,
    date: "2020-12-11",
    dateSaisie: "2020-12-11",
    valeurisee: false,
    moyenneClasse: "20.69",
    minClasse: "3.50",
    maxClasse: "33.50",
    elementsProgramme: [],
  },
  {
    devoir:
      "Travail de groupe - transposer des informations en croquis / schéma",
    codePeriode: "A002",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "8,5",
    nonSignificatif: false,
    date: "2020-12-11",
    dateSaisie: "2020-12-14",
    valeurisee: false,
    moyenneClasse: "8.14",
    minClasse: "7.50",
    maxClasse: "8.50",
    elementsProgramme: [],
  },
  {
    devoir: "DS n° 3",
    codePeriode: "A002",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "15,5",
    nonSignificatif: false,
    date: "2020-12-11",
    dateSaisie: "2021-01-05",
    valeurisee: false,
    moyenneClasse: "11.66",
    minClasse: "7.00",
    maxClasse: "16.75",
    elementsProgramme: [],
  },
  {
    devoir: "tp nrj",
    codePeriode: "A002",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "14,5",
    nonSignificatif: false,
    date: "2020-12-11",
    dateSaisie: "2021-01-13",
    valeurisee: false,
    moyenneClasse: "14.45",
    minClasse: "13.00",
    maxClasse: "16.00",
    elementsProgramme: [],
  },
  {
    devoir: "Quiz French Revolution (exhibition) - Kahoot",
    codePeriode: "A002",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18,5",
    nonSignificatif: false,
    date: "2020-12-17",
    dateSaisie: "2020-12-21",
    valeurisee: false,
    moyenneClasse: "17.75",
    minClasse: "17.00",
    maxClasse: "18.50",
    elementsProgramme: [],
  },
  {
    devoir: "Final task Topic 1",
    codePeriode: "A002",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2020-12-17",
    dateSaisie: "2020-12-21",
    valeurisee: false,
    moyenneClasse: "18.00",
    minClasse: "17.00",
    maxClasse: "19.00",
    elementsProgramme: [],
  },
  {
    devoir: "Compréhension_orale_axe4",
    codePeriode: "A002",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Examen Blanc",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "16",
    nonSignificatif: false,
    date: "2020-12-20",
    dateSaisie: "2020-12-20",
    valeurisee: false,
    moyenneClasse: "15.44",
    minClasse: "9.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Exposés",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "10",
    nonSignificatif: false,
    date: "2021-01-05",
    dateSaisie: "2021-01-05",
    valeurisee: false,
    moyenneClasse: "9.00",
    minClasse: "6.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Projet final vidéo",
    codePeriode: "A002",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro orales",
    enLettre: false,
    coef: "1.5",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-01-08",
    dateSaisie: "2021-01-08",
    valeurisee: false,
    moyenneClasse: "17.78",
    minClasse: "13.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS n° 4",
    codePeriode: "A002",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "11,5",
    nonSignificatif: false,
    date: "2021-01-15",
    dateSaisie: "2021-01-22",
    valeurisee: false,
    moyenneClasse: "10.47",
    minClasse: "3.00",
    maxClasse: "18.00",
    elementsProgramme: [],
  },
  {
    devoir: "Questionnaire lecture LP",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "16,75",
    nonSignificatif: false,
    date: "2021-01-15",
    dateSaisie: "2021-01-15",
    valeurisee: false,
    moyenneClasse: "14.48",
    minClasse: "5.00",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "Force et 2ème loi de Newton",
    codePeriode: "A002",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1.5",
    noteSur: "20",
    valeur: "10,5",
    nonSignificatif: false,
    date: "2021-01-16",
    dateSaisie: "2021-01-16",
    valeurisee: false,
    moyenneClasse: "8.83",
    minClasse: "3.50",
    maxClasse: "14.00",
    elementsProgramme: [],
  },
  {
    devoir: "Expression écrite",
    codePeriode: "A002",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2021-01-18",
    dateSaisie: "2021-01-18",
    valeurisee: false,
    moyenneClasse: "15.82",
    minClasse: "10.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Gamme tempérée",
    codePeriode: "A002",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-01-18",
    dateSaisie: "2021-01-20",
    valeurisee: false,
    moyenneClasse: "18.79",
    minClasse: "13.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Mini projet Jeu",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-01-20",
    dateSaisie: "2021-01-20",
    valeurisee: false,
    moyenneClasse: "17.04",
    minClasse: "13.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS3 Tableau",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-01-20",
    dateSaisie: "2021-01-20",
    valeurisee: false,
    moyenneClasse: "15.63",
    minClasse: "6.75",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "travail d'une force",
    codePeriode: "A002",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "2",
    noteSur: "20",
    valeur: "12,5",
    nonSignificatif: false,
    date: "2021-01-25",
    dateSaisie: "2021-02-08",
    valeurisee: false,
    moyenneClasse: "11.30",
    minClasse: "3.00",
    maxClasse: "17.50",
    elementsProgramme: [],
  },
  {
    devoir: "IE ch4 ",
    codePeriode: "A002",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2021-01-26",
    dateSaisie: "2021-01-26",
    valeurisee: false,
    moyenneClasse: "15.70",
    minClasse: "11.00",
    maxClasse: "19.00",
    elementsProgramme: [],
  },
  {
    devoir: "Project 2 - The Beatles and other famous groups",
    codePeriode: "A002",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2021-01-26",
    dateSaisie: "2021-01-26",
    valeurisee: false,
    moyenneClasse: "18.41",
    minClasse: "17.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS-Bac blanc",
    codePeriode: "A002",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "2",
    noteSur: "20",
    valeur: "13",
    nonSignificatif: false,
    date: "2021-01-27",
    dateSaisie: "2021-02-08",
    valeurisee: false,
    moyenneClasse: "13.36",
    minClasse: "5.00",
    maxClasse: "17.50",
    elementsProgramme: [],
  },
  {
    devoir: "Son",
    codePeriode: "A002",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-01-27",
    dateSaisie: "2021-01-27",
    valeurisee: false,
    moyenneClasse: "15.41",
    minClasse: "1.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Architecture_assembleur",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "27",
    valeur: "26",
    nonSignificatif: false,
    date: "2021-01-28",
    dateSaisie: "2021-02-04",
    valeurisee: false,
    moyenneClasse: "18.92",
    minClasse: "12.00",
    maxClasse: "26.00",
    elementsProgramme: [],
  },
  {
    devoir: "titrage colorimétrique",
    codePeriode: "A002",
    codeMatiere: "PH-CH",
    libelleMatiere: "PHYSIQUE-CHIMIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1.5",
    noteSur: "19",
    valeur: "16",
    nonSignificatif: false,
    date: "2021-01-29",
    dateSaisie: "2021-02-06",
    valeurisee: false,
    moyenneClasse: "16.82",
    minClasse: "15.00",
    maxClasse: "18.50",
    elementsProgramme: [],
  },
  {
    devoir: "3x500m",
    codePeriode: "A002",
    codeMatiere: "EPS",
    libelleMatiere: "ED.PHYSIQUE & SPORT.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-01-31",
    dateSaisie: "2021-01-31",
    valeurisee: false,
    moyenneClasse: "18.72",
    minClasse: "14.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Lettre 162",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "10",
    nonSignificatif: false,
    date: "2021-02-05",
    dateSaisie: "2021-02-05",
    valeurisee: false,
    moyenneClasse: "6.95",
    minClasse: "4.00",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "DS n° 5",
    codePeriode: "A002",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "14,75",
    nonSignificatif: false,
    date: "2021-02-05",
    dateSaisie: "2021-02-12",
    valeurisee: false,
    moyenneClasse: "12.00",
    minClasse: "4.50",
    maxClasse: "17.00",
    elementsProgramme: [],
  },
  {
    devoir: "EMC 2 - Débat 2 - Groupe 2",
    codePeriode: "A002",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "14",
    nonSignificatif: false,
    date: "2021-02-08",
    dateSaisie: "2021-02-08",
    valeurisee: false,
    moyenneClasse: "14.40",
    minClasse: "12.00",
    maxClasse: "17.00",
    elementsProgramme: [],
  },
  {
    devoir: "Voca_immigration",
    codePeriode: "A002",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19,5",
    nonSignificatif: false,
    date: "2021-02-08",
    dateSaisie: "2021-02-07",
    valeurisee: false,
    moyenneClasse: "17.25",
    minClasse: "10.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Fauteuil d'artiste",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-02-09",
    dateSaisie: "2021-02-09",
    valeurisee: false,
    moyenneClasse: "18.04",
    minClasse: "16.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "circuit logique",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-02-10",
    dateSaisie: "2021-02-10",
    valeurisee: false,
    moyenneClasse: "18.85",
    minClasse: "10.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "évaluation de grammaire vocabulaire",
    codePeriode: "A002",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "16",
    nonSignificatif: false,
    date: "2021-02-11",
    dateSaisie: "2021-02-11",
    valeurisee: false,
    moyenneClasse: "13.65",
    minClasse: "9.00",
    maxClasse: "17.50",
    elementsProgramme: [],
  },
  {
    devoir: "Compréhension orale",
    codePeriode: "A002",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-02-11",
    dateSaisie: "2021-02-11",
    valeurisee: false,
    moyenneClasse: "15.14",
    minClasse: "8.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "QCM réseaux",
    codePeriode: "A002",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "32",
    valeur: "28",
    nonSignificatif: false,
    date: "2021-02-11",
    dateSaisie: "2021-02-11",
    valeurisee: false,
    moyenneClasse: "21.15",
    minClasse: "7.00",
    maxClasse: "30.00",
    elementsProgramme: [],
  },
  {
    devoir: "Final tast mind the gender gap",
    codePeriode: "A002",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Devoirs",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-02-12",
    dateSaisie: "2021-02-12",
    valeurisee: false,
    moyenneClasse: "17.30",
    minClasse: "14.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Investment 2nd period",
    codePeriode: "A002",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-02-12",
    dateSaisie: "2021-02-12",
    valeurisee: false,
    moyenneClasse: "18.44",
    minClasse: "15.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Compréhension écrite",
    codePeriode: "A002",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-02-16",
    dateSaisie: "2021-02-16",
    valeurisee: false,
    moyenneClasse: "18.35",
    minClasse: "14.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "QL Rouge et noir 1",
    codePeriode: "A002",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-02-17",
    dateSaisie: "2021-03-02",
    valeurisee: false,
    moyenneClasse: "13.32",
    minClasse: "1.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "oral",
    codePeriode: "A002",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro orales",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "10",
    nonSignificatif: false,
    date: "2021-02-19",
    dateSaisie: "2021-02-18",
    valeurisee: false,
    moyenneClasse: "9.09",
    minClasse: "7.50",
    maxClasse: "10.00",
    elementsProgramme: [],
  },
  {
    devoir: "Interro n° 5",
    codePeriode: "A003",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.25",
    noteSur: "20",
    valeur: "17,5",
    nonSignificatif: false,
    date: "2021-03-05",
    dateSaisie: "2021-03-14",
    valeurisee: false,
    moyenneClasse: "12.17",
    minClasse: "4.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Schéma mental",
    codePeriode: "A003",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.25",
    noteSur: "5",
    valeur: "4",
    nonSignificatif: false,
    date: "2021-03-08",
    dateSaisie: "2021-03-22",
    valeurisee: false,
    moyenneClasse: "4.30",
    minClasse: "4.00",
    maxClasse: "5.00",
    elementsProgramme: [],
  },
  {
    devoir: "réseau - adressage",
    codePeriode: "A003",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "27",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-03-18",
    dateSaisie: "2021-03-24",
    valeurisee: false,
    moyenneClasse: "12.71",
    minClasse: "4.00",
    maxClasse: "21.75",
    elementsProgramme: [],
  },
  {
    devoir: "DS n° 6",
    codePeriode: "A003",
    codeMatiere: "MATHS",
    libelleMatiere: "MATHEMATIQUES",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "14",
    nonSignificatif: false,
    date: "2021-03-19",
    dateSaisie: "2021-03-27",
    valeurisee: false,
    moyenneClasse: "12.58",
    minClasse: "4.75",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "Interrogation ",
    codePeriode: "A003",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "0.5",
    noteSur: "20",
    valeur: "18,5",
    nonSignificatif: false,
    date: "2021-03-21",
    dateSaisie: "2021-03-21",
    valeurisee: false,
    moyenneClasse: "16.90",
    minClasse: "11.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "conjugaison_passé",
    codePeriode: "A003",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-03-21",
    dateSaisie: "2021-03-15",
    valeurisee: false,
    moyenneClasse: "16.14",
    minClasse: "7.50",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Production graphique - travail en binôme",
    codePeriode: "A003",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "0.5",
    noteSur: "10",
    valeur: "6,5",
    nonSignificatif: false,
    date: "2021-03-22",
    dateSaisie: "2021-03-22",
    valeurisee: false,
    moyenneClasse: "7.33",
    minClasse: "6.50",
    maxClasse: "9.00",
    elementsProgramme: [],
  },
  {
    devoir: "Numérisation",
    codePeriode: "A003",
    codeMatiere: "ENSC",
    libelleMatiere: "ENSEIGNEMENT SCIENTIFIQUE",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: true,
    coef: "1",
    noteSur: "20",
    valeur: "Abs ",
    nonSignificatif: false,
    date: "2021-03-22",
    dateSaisie: "2021-03-30",
    valeurisee: false,
    moyenneClasse: "",
    minClasse: "",
    maxClasse: "",
    elementsProgramme: [],
  },
  {
    devoir: "Évaluation Commune Production graphique",
    codePeriode: "A003",
    codeMatiere: "HI-GE",
    libelleMatiere: "HISTOIRE-GEOGRAPHIE",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "10",
    valeur: "7,5",
    nonSignificatif: true,
    date: "2021-03-29",
    dateSaisie: "2021-04-08",
    valeurisee: false,
    moyenneClasse: "7.37",
    minClasse: "6.00",
    maxClasse: "9.50",
    elementsProgramme: [],
  },
  {
    devoir: "Final task Topic 2",
    codePeriode: "A003",
    codeMatiere: "AGL9",
    libelleMatiere: "ANGLAIS LV SECTION",
    codeSousMatiere: "",
    typeDevoir: "Travaux Divers",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "18",
    nonSignificatif: false,
    date: "2021-04-01",
    dateSaisie: "2021-04-01",
    valeurisee: false,
    moyenneClasse: "17.88",
    minClasse: "17.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "Bac blanc",
    codePeriode: "A003",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Examen Blanc",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "14",
    nonSignificatif: true,
    date: "2021-04-01",
    dateSaisie: "2021-04-01",
    valeurisee: false,
    moyenneClasse: "12.63",
    minClasse: "0.00",
    maxClasse: "18.00",
    elementsProgramme: [],
  },
  {
    devoir: "Type construit",
    codePeriode: "A003",
    codeMatiere: "NSINF",
    libelleMatiere: "NUMERIQUE SC.INFORM.",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "20",
    nonSignificatif: false,
    date: "2021-04-02",
    dateSaisie: "2021-04-02",
    valeurisee: false,
    moyenneClasse: "17.36",
    minClasse: "11.75",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "compréhension de l'écrit",
    codePeriode: "A003",
    codeMatiere: "AGL1",
    libelleMatiere: "ANGLAIS LV1",
    codeSousMatiere: "",
    typeDevoir: "Devoirs surveillés",
    enLettre: false,
    coef: "1",
    noteSur: "20",
    valeur: "16",
    nonSignificatif: false,
    date: "2021-04-07",
    dateSaisie: "2021-04-07",
    valeurisee: false,
    moyenneClasse: "14.38",
    minClasse: "9.00",
    maxClasse: "20.00",
    elementsProgramme: [],
  },
  {
    devoir: "EE_immigration",
    codePeriode: "A003",
    codeMatiere: "ESP2",
    libelleMatiere: "ESPAGNOL LV2",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: false,
    coef: "1.5",
    noteSur: "20",
    valeur: "19",
    nonSignificatif: false,
    date: "2021-04-08",
    dateSaisie: "2021-04-08",
    valeurisee: false,
    moyenneClasse: "18.21",
    minClasse: "15.00",
    maxClasse: "19.50",
    elementsProgramme: [],
  },
  {
    devoir: "Questionnaire de lecture RetN II",
    codePeriode: "A003",
    codeMatiere: "FRANC",
    libelleMatiere: "FRANCAIS",
    codeSousMatiere: "",
    typeDevoir: "Interro écrites",
    enLettre: true,
    coef: "0.5",
    noteSur: "20",
    valeur: "Abs ",
    nonSignificatif: false,
    date: "2021-04-09",
    dateSaisie: "2021-04-09",
    valeurisee: false,
    moyenneClasse: "",
    minClasse: "",
    maxClasse: "",
    elementsProgramme: [],
  },
];

const parametrage = {
  couleurEval1: "#FF0000",
  couleurEval2: "#FFC000",
  couleurEval3: "#0070C0",
  couleurEval4: "#00B050",
  libelleEval1: "Tm9uIGF0dGVpbnRz",
  libelleEval2: "UGFydGllbGxlbWVudCBhdHRlaW50cw==",
  libelleEval3: "QXR0ZWludHM=",
  libelleEval4: "RMOpcGFzc8Opcw==",
  affichageMoyenne: true,
  affichageMoyenneDevoir: true,
  affichagePositionMatiere: false,
  affichageNote: true,
  affichageCompetence: false,
  affichageEvaluationsComposantes: false,
  affichageGraphiquesComposantes: true,
  modeCalculGraphiquesComposantes: "eval",
  affichageCompNum: false,
  libelleEvalCompNum1: "Tm9uIGF0dGVpbnQ=",
  libelleEvalCompNum2: "UGFydGllbGxlbWVudCBhdHRlaW50",
  libelleEvalCompNum3: "QXR0ZWludA==",
  affichageAppreciation: false,
  appreciationsProf: false,
  appreciationProfPrinc: false,
  affichageMention: false,
  affichageAppreciationCE: false,
  affichageAppreciationVS: false,
  affichageAppreciationCN: false,
  affichageAppreciationClasse: false,
  affichageAppreciationPeriodeCloturee: false,
  moyenneUniquementPeriodeCloture: false,
  moyennePeriodeReleve: true,
  moyennePeriodeAnnuelle: false,
  moyennePeriodeHorsP: false,
  moyenneEleveDansNotes: true,
  moyenneEleve: true,
  moyenneEleveDansMoyenne: true,
  moyenneGenerale: true,
  moyenneCoefMatiere: true,
  moyenneClasse: true,
  moyenneMin: true,
  moyenneMax: true,
  moyenneRang: false,
  moyenneSur: 20,
  moyenneGraphique: false,
  moyennesSimulation: false,
  coefficientNote: true,
  colonneCoefficientMatiere: true,
  noteGrasSousMoyenne: true,
  noteGrasAudessusMoyenne: false,
  libelleDevoir: true,
  dateDevoir: true,
  typeDevoir: true,
  noteUniquementPeriodeCloture: false,
  notePeriodeReleve: true,
  notePeriodeAnnuelle: false,
  notePeriodeHorsP: false,
  libellesAppreciations: ["Appréciation générale"],
  appreciationsParametrage: [
    {
      code: "APP1",
      id: 1,
      nbMaxCaractere: 200,
      libelle: "Appréciation générale",
    },
  ],
};

const grades = {
  periodes,
  notes,
  parametrage,
};

export default grades;
