const mails = {
  classeurs: [
    {
      id: 523,
      libelle: "Grand oral",
    },
  ],
  messages: {
    received: [
      {
        id: 85090,
        mtype: "received",
        read: true,
        idDossier: -1,
        idClasseur: 0,
        transferred: false,
        answered: false,
        to_cc_cci: "to",
        brouillon: false,
        subject: "Utilisez yNotes plutôt que Ecole Directe",
        content: "",
        date: "2021-07-06 21:41:44",
        to: [],
        files: [],
        from: {
          name: "M Michel BLANQUER",
          nom: "BLANQUER",
          prenom: "Michel",
          particule: "",
          civilite: "M",
          role: "P",
          listeRouge: false,
          id: 129,
          read: true,
          fonctionPersonnel: "",
        },
      },
      {
        id: 85078,
        mtype: "received",
        read: true,
        idDossier: -1,
        idClasseur: 0,
        transferred: false,
        answered: true,
        to_cc_cci: "to",
        brouillon: false,
        subject: "Adieu !",
        content: "",
        date: "2021-07-06 17:51:24",
        to: [],
        files: [],
        from: {
          name: "M JEAN GAUTIER",
          nom: "GAUTIER",
          prenom: "JEAN",
          particule: "",
          civilite: "M",
          role: "P",
          listeRouge: false,
          id: 128,
          read: true,
          fonctionPersonnel: "",
        },
      },
      {
        id: 85035,
        mtype: "received",
        read: true,
        idDossier: -1,
        idClasseur: 0,
        transferred: false,
        answered: false,
        to_cc_cci: "to",
        brouillon: false,
        subject: "Fin des cours : ne revenez pas svp",
        content: "",
        date: "2021-07-06 09:39:28",
        to: [],
        files: [],
        from: {
          name: "Mme VALERIE AUCO",
          nom: "AUCO",
          prenom: "VALERIE",
          particule: "",
          civilite: "Mme",
          role: "A",
          listeRouge: true,
          id: 19,
          read: true,
          fonctionPersonnel: "",
        },
      },
      {
        id: 84976,
        mtype: "received",
        read: true,
        idDossier: -1,
        idClasseur: 0,
        transferred: false,
        answered: false,
        to_cc_cci: "to",
        brouillon: false,
        subject: "Vente de brioche",
        content: "",
        date: "2021-07-05 11:37:15",
        to: [],
        files: [],
        from: {
          name: "Mme ANTOINETTE MARIE",
          nom: "ANTOINETTE",
          prenom: "MARIE",
          particule: "",
          civilite: "Mme",
          role: "A",
          listeRouge: false,
          id: 132,
          read: true,
          fonctionPersonnel: "",
        },
      },
      {
        id: 84576,
        mtype: "received",
        read: true,
        idDossier: -1,
        idClasseur: 0,
        transferred: false,
        answered: false,
        to_cc_cci: "to",
        brouillon: false,
        subject: "Résultats du bac (c'est pas terrible)",
        content: "",
        date: "2021-06-29 14:27:48",
        to: [],
        files: [],
        from: {
          name: "Mme VALERIE AUCO",
          nom: "AUCO",
          prenom: "VALERIE",
          particule: "",
          civilite: "Mme",
          role: "A",
          listeRouge: true,
          id: 19,
          read: true,
          fonctionPersonnel: "",
        },
      },
    ],
    sent: [],
    draft: [],
    archived: [],
  },
  parametrage: {
    isActif: true,
    canParentsLireMessagesEnfants: true,
    destAdmin: false,
    destEleve: false,
    destFamille: false,
    destProf: false,
    destEspTravail: true,
    disabledNotification: false,
    notificationEmailEtablissement: true,
    choixMailNotification: 0,
    autreMailNotification: "",
    mailPro: "",
    mailPerso: "",
    messagerieApiVersion: "v3",
    blackListProfActive: false,
    estEnBlackList: false,
    afficherToutesLesClasses: false,
  },
  pagination: {
    messagesRecusCount: 250,
    messagesEnvoyesCount: 0,
    messagesArchivesCount: 0,
    messagesRecusNotReadCount: 0,
  },
};

export default mails;