const workspaces = [
  {
    id: 29,
    titre: "Espace de travail Seconde A",
    description: "",
    resume: "RXNwYWNlIGRlIHRyYXZhaWwgZGUgbGEgY2xhc3NlIFByZW1pw6hyZSBE",
    cloud: true,
    discussion: true,
    agenda: true,
    public: false,
    ouvert: false,
    type: "ORGA",
    estMembre: true,
    estAdmin: false,
    salleDesProfs: false,
    creePar: "",
    droitUtilisateur: 1,
    nbMembres: 0,
    couleurEvenementAgenda: "#1796b0",
  },
  {
    id: 79,
    titre: "Espace de travail Spécialité Physique",
    description: "",
    resume:
      "ZXNwYWNlIGRlIHRyYXZhaWwgcG91ciBsZXMgZ3JvdXBlcyBkZSBzcMOpY2lhbGl0w6lzIHBoeXNpcXVl\nLWNoaW1pZQ==",
    cloud: true,
    discussion: true,
    agenda: true,
    public: false,
    ouvert: false,
    type: "LIBRE",
    estMembre: true,
    estAdmin: false,
    salleDesProfs: false,
    creePar: "M. MARTIN",
    creeLe: "09/04/2021 à 11:59",
    droitUtilisateur: 1,
    nbMembres: 0,
    couleurEvenementAgenda: "#33cc33",
  },
];

export default workspaces;
